# Generated by Django 5.1.4 on 2025-01-08 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
    ]
